name: Develop
on:
  push:
    branches:
      - develop
jobs:
  demo:
    name: Demo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Bundle 📦
        run: |
          npm ci
          npm run build
      - name: Install and Build Demo 🔧
        working-directory: demo
        run: npx vite build --base "/mapbox-gl-draw-split-polygon-mode/"
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: demo/dist # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
